<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MaestrosSeeder extends Seeder
{
    public function run()
    {
        $maestros = [
            [
                'apellido_paterno' => 'APARICIO',
                'apellido_materno' => 'AMES',
                'nombres' => 'MARIA GRICELDA',
                'grado_estudios' => 'LIC.',
                'rfc' => 'AAAG5508124X2',
                'curp' => 'AAAG550812MBCPMR02',
                'tarjeta_recursos_humanos' => '16',
                'fecha_nacimiento' => '1955-08-12',
                'area_administrativa' => 1,
                'sexo' => 'F',
                'estado_civil' => 'CASADA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1981-09-01'
            ],
            [
                'apellido_paterno' => 'ALVARADO',
                'apellido_materno' => 'GONZALEZ',
                'nombres' => 'EVARISTO',
                'grado_estudios' => 'ING.',
                'rfc' => 'AAGE470703RR6',
                'curp' => 'AAGE470703HBCPLR01',
                'tarjeta_recursos_humanos' => '1100',
                'fecha_nacimiento' => '1947-07-03',
                'area_administrativa' => 2,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1969-09-01'
            ],
            [
                'apellido_paterno' => 'AGAPITO',
                'apellido_materno' => 'GONZALEZ',
                'nombres' => 'JAIME OCTAVIO',
                'grado_estudios' => 'ING.',
                'rfc' => 'AAGJ5911095Y2',
                'curp' => 'AAGJ591109HMCGNM08',
                'tarjeta_recursos_humanos' => '1152',
                'fecha_nacimiento' => '1959-11-09',
                'area_administrativa' => 3,
                'sexo' => 'M',
                'estado_civil' => 'CASADO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '2007-01-01'
            ],
            [
                'apellido_paterno' => 'ALVARADO',
                'apellido_materno' => 'MARTINEZ',
                'nombres' => 'PERLA LIZ',
                'grado_estudios' => 'SEC.',
                'rfc' => 'AAMP781010124',
                'curp' => 'AAMP781010MBCLRRU9',
                'tarjeta_recursos_humanos' => '1515',
                'fecha_nacimiento' => '1978-10-10',
                'area_administrativa' => 4,
                'sexo' => 'F',
                'estado_civil' => 'VIUDA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '2011-09-01'
            ],
            [
                'apellido_paterno' => 'ACOSTA',
                'apellido_materno' => 'CASTILLO',
                'nombres' => 'ANTONIO',
                'grado_estudios' => 'ING.',
                'rfc' => 'AOCA410706BH8',
                'curp' => 'AOCA410706HMCCSN14',
                'tarjeta_recursos_humanos' => '928',
                'fecha_nacimiento' => '1941-07-06',
                'area_administrativa' => 7,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1992-09-01'
            ],
            [
                'apellido_paterno' => 'ARCOS',
                'apellido_materno' => '',
                'nombres' => 'LAURA ARABELA',
                'grado_estudios' => 'M.C.',
                'rfc' => 'AOLA620822C96',
                'curp' => 'AOLA620822MJCRXR09',
                'tarjeta_recursos_humanos' => '683',
                'fecha_nacimiento' => '1962-08-22',
                'area_administrativa' => 2,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1990-01-01'
            ],
            [
                'apellido_paterno' => 'BARRAGAN',
                'apellido_materno' => 'GALLARDO',
                'nombres' => 'LEANDRO',
                'grado_estudios' => 'ING.',
                'rfc' => 'BAGL520429HW5',
                'curp' => 'BAGL520429HJCRLN06',
                'tarjeta_recursos_humanos' => '73',
                'fecha_nacimiento' => '1952-04-29',
                'area_administrativa' => 2,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1981-04-01'
            ],
            [
                'apellido_paterno' => 'BECERRIL',
                'apellido_materno' => 'LOPEZ',
                'nombres' => 'FELIX ERNESTO',
                'grado_estudios' => 'QUI.',
                'rfc' => 'BELF470914GT1',
                'curp' => 'BELF470914HMCPLX01',
                'tarjeta_recursos_humanos' => '36',
                'fecha_nacimiento' => '1947-02-14',
                'area_administrativa' => 1,
                'sexo' => 'M',
                'estado_civil' => 'CASADO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1969-01-01'
            ],
            [
                'apellido_paterno' => 'BIRRUETA',
                'apellido_materno' => 'RUIZ',
                'nombres' => 'RAFAEL',
                'grado_estudios' => 'MAE.',
                'rfc' => 'BIRR5601148T4',
                'curp' => 'BIRR560114HMNRZF06',
                'tarjeta_recursos_humanos' => '665',
                'fecha_nacimiento' => '1956-01-14',
                'area_administrativa' => 3,
                'sexo' => 'M',
                'estado_civil' => 'CASADO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1980-03-01'
            ],
            [
                'apellido_paterno' => 'BOLAÑOS',
                'apellido_materno' => 'DIEGO',
                'nombres' => 'CARLOS JAVIER',
                'grado_estudios' => 'ING.',
                'rfc' => 'BODC590425SD0',
                'curp' => 'BODC590425HOCLGR07',
                'tarjeta_recursos_humanos' => '275',
                'fecha_nacimiento' => '1959-04-25',
                'area_administrativa' => 8,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '2008-09-01'
            ],
            [
                'apellido_paterno' => 'BOLAÑOS',
                'apellido_materno' => 'MORALES',
                'nombres' => 'DELIA',
                'grado_estudios' => 'CON.',
                'rfc' => 'BOMD570628P22',
                'curp' => 'BOMD570628MBCLRL06',
                'tarjeta_recursos_humanos' => '276',
                'fecha_nacimiento' => '1957-06-28',
                'area_administrativa' => 8,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1991-02-01'
            ],
            [
                'apellido_paterno' => 'CASTILLO',
                'apellido_materno' => 'JASSO',
                'nombres' => 'MIGUEL SERGIO',
                'grado_estudios' => 'LIC.',
                'rfc' => 'CAJM510906515',
                'curp' => 'CAJM510906HBCSSG00',
                'tarjeta_recursos_humanos' => '66',
                'fecha_nacimiento' => '1951-09-06',
                'area_administrativa' => 9,
                'sexo' => 'M',
                'estado_civil' => 'CASADO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1976-02-01'
            ],
            [
                'apellido_paterno' => 'DAVILA',
                'apellido_materno' => 'INFANTE',
                'nombres' => 'ANTONIO',
                'grado_estudios' => 'M.C.',
                'rfc' => 'DAIA450613FT4',
                'curp' => 'DAIA450613HDGVNN00',
                'tarjeta_recursos_humanos' => '84',
                'fecha_nacimiento' => '1945-06-13',
                'area_administrativa' => 1,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1983-02-01'
            ],
            [
                'apellido_paterno' => 'DIAZ',
                'apellido_materno' => 'BARRIOS',
                'nombres' => 'CONSUELO',
                'grado_estudios' => 'SEC.',
                'rfc' => 'DIBC570304QZA',
                'curp' => 'DIBC570304MTSZRN03',
                'tarjeta_recursos_humanos' => '354',
                'fecha_nacimiento' => '1957-03-04',
                'area_administrativa' => 8,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1982-10-01'
            ],
            [
                'apellido_paterno' => 'DIAZ',
                'apellido_materno' => 'GARCIA',
                'nombres' => 'JUAN ALFONSO',
                'grado_estudios' => 'M.C',
                'rfc' => 'DIGJ5209198V6',
                'curp' => 'DIGJ520919HMCPLN01',
                'tarjeta_recursos_humanos' => '991',
                'fecha_nacimiento' => '1952-09-19',
                'area_administrativa' => 7,
                'sexo' => 'M',
                'estado_civil' => 'SOLTERO',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1987-03-16'
            ],
            [
                'apellido_paterno' => 'FARIAS',
                'apellido_materno' => 'DIAZ',
                'nombres' => 'DORIDELIA',
                'grado_estudios' => '',
                'rfc' => 'FADD510101BS6',
                'curp' => 'FADD510101MJCRZR05',
                'tarjeta_recursos_humanos' => '850',
                'fecha_nacimiento' => '1951-01-01',
                'area_administrativa' => 5,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1991-09-01'
            ],
            [
                'apellido_paterno' => 'GARCIA',
                'apellido_materno' => 'VELASCO',
                'nombres' => 'BEIRA',
                'grado_estudios' => 'ING.',
                'rfc' => 'GAVB501129M67',
                'curp' => 'GAVB501129HMCPLR01',
                'tarjeta_recursos_humanos' => '134',
                'fecha_nacimiento' => '1950-11-29',
                'area_administrativa' => 6,
                'sexo' => 'F',
                'estado_civil' => 'CASADA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1974-09-01'
            ],
            [
                'apellido_paterno' => 'GUISADO',
                'apellido_materno' => 'VALDEZ',
                'nombres' => 'BLANCA ESTELA',
                'grado_estudios' => '.',
                'rfc' => 'GUVB510126KQ5',
                'curp' => 'GUVB510126MSRSLL01',
                'tarjeta_recursos_humanos' => '155',
                'fecha_nacimiento' => '1951-01-26',
                'area_administrativa' => 6,
                'sexo' => 'F',
                'estado_civil' => 'VIUDA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1978-10-01'
            ],
            [
                'apellido_paterno' => 'HERMOSILLO',
                'apellido_materno' => 'GARCIA DE ALBA',
                'nombres' => 'LUZ MARIA',
                'grado_estudios' => 'SEC',
                'rfc' => 'HEGL590123QG1',
                'curp' => 'HEGL590123MJCRRZ09',
                'tarjeta_recursos_humanos' => '866',
                'fecha_nacimiento' => '1959-01-23',
                'area_administrativa' => 4,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1991-11-01'
            ],
            [
                'apellido_paterno' => 'MICHEL',
                'apellido_materno' => 'ANGUIANO',
                'nombres' => 'M ESTELA',
                'grado_estudios' => 'CON.',
                'rfc' => 'MIAM550223863',
                'curp' => 'MIAE550223MCMCNS11',
                'tarjeta_recursos_humanos' => '968',
                'fecha_nacimiento' => '1955-02-23',
                'area_administrativa' => 4,
                'sexo' => 'F',
                'estado_civil' => 'CASADA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1993-10-16'
            ],
            [
                'apellido_paterno' => 'MIRANDA',
                'apellido_materno' => 'VEJAR',
                'nombres' => 'ELVA NORA',
                'grado_estudios' => 'SEC.',
                'rfc' => 'MIVE541116BW9',
                'curp' => 'MIVE541116MSRRJL01',
                'tarjeta_recursos_humanos' => '1085',
                'fecha_nacimiento' => '1954-11-16',
                'area_administrativa' => 9,
                'sexo' => 'F',
                'estado_civil' => 'SOLTERA',
                'lugar_nacimiento' => 'TIJUANA',
                'fecha_ingreso' => '1997-10-16'
            ]
        ];

        foreach ($maestros as $maestro) {
            DB::table('maestros')->insert($maestro);
        }
    }
}